workspace:
  base: /workspace
  path: app

when:
  - event: push
    branch: main
    path:
      include:
        - "**/*.go"
        - "**/*.gohtml"
        - ".woodpecker/build-docker.yml"
        - "Dockerfile"
      exclude:
        - "**/*.md"
      on_empty: true
  - event: tag
    ref: "refs/tags/v*.*.*"

steps:
  vendor:
    image: golang:1.24.5-alpine
    commands:
      - go mod vendor
  lint:
    image: golang:1.24.5-alpine
    commands:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.3.0
      - golangci-lint run -v
  test:
    image: golang:1.24.5-alpine
    commands:
      - ./scripts/check-coverage.sh 60

  extract-semver-tags:
    image: alpine/git:latest # A small image with git and shell tools
    commands:
      - |
        VERSION_FULL="${CI_COMMIT_TAG#v}"
        VERSION_MAJOR=$(echo "$VERSION_FULL" | cut -d. -f1)
        VERSION_MINOR=$(echo "$VERSION_FULL" | cut -d. -f2)
        
        echo "Extracted versions: Full=$VERSION_FULL, Major=$VERSION_MAJOR, Minor=$VERSION_MINOR"
        
        export SEMVER_FULL="$VERSION_FULL"
        export SEMVER_MAJOR_MINOR="${VERSION_MAJOR}.${VERSION_MINOR}"
        export SEMVER_MAJOR="$VERSION_MAJOR"
    when:
      - event: tag
        ref: "refs/tags/v*.*.*"

  build-docker-main:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      repo: git.eleith.com/eleith.private/readeckobo
      username: eleith
      dockerfile: Dockerfile
      registry: https://git.eleith.com
      password:
        from_secret: gitea_docker_registry
      tags:
        - latest
    when:
      - event: push
        branch: main

  build-docker-tag:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      repo: git.eleith.com/eleith.private/readeckobo
      username: eleith
      dockerfile: Dockerfile
      registry: https://git.eleith.com
      password:
        from_secret: gitea_docker_registry
      tags:
        - "${SEMVER_FULL}"
        - "${SEMVER_MAJOR_MINOR}"
        - "${SEMVER_MAJOR}"
    when:
      - event: tag
        ref: "refs/tags/v*.*.*"

  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]
  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
